//! Main binary entry point for openapi_client implementation.

use httpd_util::{get_server_addr, https, init_app, ssl};
use log::{debug};

#[path = "server.rs"] mod server;

/// Create custom server, wire it to the autogenerated router,
/// and pass it to the web server.
fn main() {
    init_app(
        "i2cbus",
        "Piers Finlayson, piers@piersandkatie.com",
        "An HTTP(S) microservice exposing I2C bus functionality",
        vec![],
        vec![],
    );

    let ssl = match https() {
        true => Some(ssl().unwrap()),
        _ => None,
    };
    match ssl {
        Some(_) => debug!("Using SSL"),
        None => debug!("Not using SSL"),
    }

    let addr_socket = get_server_addr();
    let addr_string = format!("{}:{}", addr_socket.ip(), addr_socket.port());
    debug!("Bind to: {}", addr_string);
    hyper::rt::run(server::create(&addr_string, ssl));
}
